## Bert cosine similarity

In [ ]:
import random
import numpy as np
from transformers import BertTokenizer, TFBertModel
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# # Set a random seed
# random_seed = 42
# random.seed(random_seed)

# # Set a random seed for PyTorch (for GPU as well)
# torch.manual_seed(random_seed)
# if torch.cuda.is_available():
#     torch.cuda.manual_seed_all(random_seed)

# Load BERT tokenizer and model
# tokenizer_bert = BertTokenizer.from_pretrained('bert-base-uncased')
# model_bert = BertModel.from_pretrained('bert-base-uncased')

In [ ]:
# def bert_embedding(example_sentence, model=model_bert, tokenizer=tokenizer_bert):

#   # Tokenize and encode the example sentence
#   example_encoding = tokenizer.batch_encode_plus(
#       [example_sentence],
#       padding=True,
#       truncation=True,
#       return_tensors='pt',
#       add_special_tokens=True
#   )
#   example_input_ids = example_encoding['input_ids']
#   example_attention_mask = example_encoding['attention_mask']

#   # Generate embeddings for the example sentence
#   with torch.no_grad():
#       example_outputs = model(example_input_ids, attention_mask=example_attention_mask)
#       example_sentence_embedding = example_outputs.last_hidden_state.mean(dim=1)

#   return example_sentence_embedding

In [ ]:
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
bert_model = TFBertModel.from_pretrained('bert-base-cased')

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [ ]:
def cosine_sim(a,b):
  similarity_score = cosine_similarity(a, b)[0]
  return similarity_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
target_sen_1 = np.load('/content/drive/MyDrive/capstone_annie/true_sen_10_22_150.npy')
target_sen_2 = np.load('/content/drive/MyDrive/capstone_annie/true_sen_10_22_180.npy')
target_sen_3 = np.load('/content/drive/MyDrive/capstone_annie/true_sen_10_22_300.npy')
target_sen_4 = np.load('/content/drive/MyDrive/capstone_annie/true_sen_10_22_331.npy')
target_sen_5 = np.load('/content/drive/MyDrive/capstone_annie/true_sen_10_22_480.npy')
target_sen_6 = np.load('/content/drive/MyDrive/capstone_annie/true_sen_10_22_500.npy')


pred_sen_1 = np.load('/content/drive/MyDrive/capstone_annie/pred_10_22_150.npy')
pred_sen_2 = np.load('/content/drive/MyDrive/capstone_annie/pred_10_22_180.npy')
pred_sen_3 = np.load('/content/drive/MyDrive/capstone_annie/pred_10_22_300.npy')
pred_sen_4 = np.load('/content/drive/MyDrive/capstone_annie/pred_10_22_331.npy')
pred_sen_5 = np.load('/content/drive/MyDrive/capstone_annie/pred_10_22_480.npy')
pred_sen_6 = np.load('/content/drive/MyDrive/capstone_annie/pred_10_22_500.npy')

target_sen = np.vstack((target_sen_1, target_sen_2, target_sen_3, target_sen_4, target_sen_5, target_sen_6))
pred_sen = np.vstack((pred_sen_1, pred_sen_2, pred_sen_3, pred_sen_4, pred_sen_5, pred_sen_6))

In [ ]:
target_sen[0][0]

'This is an aluminum can. It can be recycled in Cook County. Please dispense it in the nearest recycling can.'

In [ ]:
bert_tokenizer([target_sen[0][0]],
                                 max_length=30,
                                 truncation=True,
                                 padding='max_length',
                                 return_tensors='tf')

{'input_ids': <tf.Tensor: shape=(1, 30), dtype=int32, numpy=
array([[  101,  1188,  1110,  1126, 14349,  1169,   119,  1135,  1169,
         1129, 25677,  1107,  6816,  1391,   119,  4203,  4267, 21643,
         1122,  1107,  1103,  6830, 21804,  1169,   119,   102,     0,
            0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 30), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 30), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 0, 0]], dtype=int32)>}

In [ ]:
target_input = bert_tokenizer(target_sen.reshape(target_sen.shape[0]).tolist(),
                                 max_length=30,
                                 truncation=True,
                                 padding='max_length',
                                 return_tensors='tf')

target_outputs = bert_model(target_input)
target_embeddings = target_outputs[0]
target_embedding_flat = target_embeddings.numpy().reshape(target_embeddings.shape[0], -1)

In [ ]:
pred_input = bert_tokenizer(pred_sen.reshape(pred_sen.shape[0]).tolist(),
                                 max_length=30,
                                 truncation=True,
                                 padding='max_length',
                                 return_tensors='tf')

pred_outputs = bert_model(pred_input)
pred_embeddings = pred_outputs[0]
pred_embedding_flat = pred_embeddings.numpy().reshape(pred_embeddings.shape[0], -1)

In [ ]:
arr = np.array([[[1, 2], [5, 2]], [[3, 4], [5, 6]]])
arr.shape

arr.reshape(arr.shape[0], -1)

array([[1, 2, 5, 2],
       [3, 4, 5, 6]])

In [ ]:
cosine_sim_list = []
for i in range(target_sen.shape[0]):
  cosine_sim_list.append(cosine_sim([target_embedding_flat[i]], [pred_embedding_flat[i]]))

cosine_sim_list_not_flat = []
for i in range(target_sen.shape[0]):
  cosine_sim_list_not_flat.append(cosine_sim(target_embeddings[i], pred_embeddings[i]))

In [ ]:
np.mean(cosine_sim_list)

0.5247056

In [ ]:
np.mean(cosine_sim_list_not_flat)

0.26269627

##### Baseline

In [ ]:
t_sen = np.load("/content/drive/My Drive/capstone_annie/res_net_10_29_true.npy")
p_sen = np.load("/content/drive/My Drive/capstone_annie/res_net_10_29_pred.npy")

In [ ]:
target_input = bert_tokenizer(t_sen.tolist(),
                                 max_length=30,
                                 truncation=True,
                                 padding='max_length',
                                 return_tensors='tf')

target_outputs = bert_model(target_input)
target_embeddings = target_outputs[0]
target_embedding_flat = target_embeddings.numpy().reshape(target_embeddings.shape[0], -1)

In [ ]:
pred_input = bert_tokenizer(p_sen.tolist(),
                                 max_length=30,
                                 truncation=True,
                                 padding='max_length',
                                 return_tensors='tf')

pred_outputs = bert_model(pred_input)
pred_embeddings = pred_outputs[0]
pred_embedding_flat = pred_embeddings.numpy().reshape(pred_embeddings.shape[0], -1)

In [ ]:
cosine_sim_list = []
for i in range(true_sen.shape[0]):
  cosine_sim_list.append(cosine_sim([target_embedding_flat[i]], [pred_embedding_flat[i]]))

np.mean(cosine_sim_list)

0.97334605

## BLEU Score

In [ ]:
!pip install -q evaluate
import evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.7/472.7 kB 25.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 7.8 MB/s eta 0:00:00


###### llava

In [ ]:
ref_list = target_sen.reshape(target_sen.shape[0]).tolist()
pred_list = pred_sen.reshape(pred_sen.shape[0]).tolist()

In [ ]:
bleu = evaluate.load('bleu')

results = bleu.compute(predictions=pred_list,
                        references=ref_list,
                       max_order=1) # set n-gram
print(results)

{'bleu': 0.22490931076178958, 'precisions': [0.2249093107617896], 'brevity_penalty': 1.0, 'length_ratio': 2.486944403696641, 'translation_length': 33907, 'reference_length': 13634}


##### baseline

In [ ]:
ref_list = t_sen.tolist()
pred_list = p_sen.tolist()

In [ ]:
bleu = evaluate.load('bleu')

results = bleu.compute(predictions=pred_list,
                        references=ref_list,
                       max_order=1) # set n-gram
print(results)

{'bleu': 0.9646353015472056, 'precisions': [0.9646353015472056], 'brevity_penalty': 1.0, 'length_ratio': 1.004121750158529, 'translation_length': 3167, 'reference_length': 3154}
